# Generated by Django 4.2.6 on 2023-10-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('release_date', models.DateTimeField()),
                ('running_time', models.IntegerField()),
                ('budget', models.IntegerField(blank=True)),
                ('tmdb_id', models.IntegerField(blank=True, unique=True)),
                ('revenue', models.IntegerField(blank=True)),
                ('poster_path', models.URLField(blank=True)),
            ],
        ),
    ]
